### ISSUE TITLE
Incompatibilidade com tema

### ISSUE THREAD

**Issue by EdRolla** [rosantoz/correios-magento#1]
Opa! 

Primeiramente, nada menos do que excelente trabalho!!! Parabéns!

Já utilizei o módulo em vários temas e sempre funcionou perfeitamente. Porém, no último, a diferença é que o tema está instalado (ao invés de "app\design\frontend\dafult\default") em "app\design\frontend\meu_tema\uma_variacao". 

O problema ocorre ao tentar finalizar o pedido. A terceira etapa (Escolha do frete) não carrega ao clicar no botão "Continuar".

Alguma sugestão de como posso contornar o problema?

Grato,
Edgar

**Comment by rosantoz** [comment]
Olá Edgar.

Qual seria este tema? Quero instalar ele aqui para tentar simular o problema.

**Comment by EdRolla** [comment]
Fala, Santoz.
Cara, o tema é pago.... tá instalado aqui: http://keepplaying.com.br/magento/

Se eu te passar não dá m\* com a licença, não? Só fico preocupado com isso... passa seu e-mail para eu te passar o link para download do tema.

abraço!

**Comment by rosantoz** [comment]
falecom [arroba] rodrigodossantos.ws

Irei apenas instalar localmente para ver se identifico o problema.
