### ISSUE TITLE
Alterar peso para gramas

### ISSUE THREAD

**Issue by phdiegues** [rosantoz/correios-magento#4]
olá pesoal. Instalei o Modulo, excelente por sinal e vi que ele precisa ter o peso dos produtos em Kg, como eu poderia altera-lo para gramas, pois tenho quase 2000 produtos para alterar o peso. =/

Agradeço muito por qualquer ajuda.

Abraços!

**Comment by rosantoz** [comment]
Para conseguir isto você teria que fazer uma pequena alteração no código.

Converta o peso do produto de para de gramas para Kg nesta linha: 
https://github.com/rosantoz/correios-magento/blob/master/app/code/community/Rosantoz/Correios/Model/Carrier/Correios.php#L68
